os: linux
dist: bionic
language: node_js
node_js:
  - 12
  - 10
  - 8
script: "npm run test:cov"

jobs:
  include:
    - node_js: stable
      after_script: |
        npm i -g codecov
        npx nyc report --reporter=text-lcov | codecov --pipe
    # Node.js 6 is not supported by nyc, so run tests without code coverage
    - node_js: 6
      script: npm run test
