os: linux
dist: bionic
language: node_js
node_js:
  - 12
  - 10
  - 8
  - 6
  - 4
script: "npm run test:cov"

jobs:
  include:
    - node_js: stable
      after_script: |
        npm i -g codecov.io
        cat ./coverage/lcov.info | codecov
